<template>
  <main>
    <h1>Home</h1>
    <h1>Home</h1>
    <h1>Home</h1>
    <h1>Home</h1>
    <h1>Home</h1>
    <h1>Home</h1>
    <h1>Home</h1>
    <h1>Home</h1>
    <h1>Home</h1>
    <h1>Home</h1>
    <h1>Home</h1>
    <h1>Home</h1>
    <h1>Home</h1>
     <h1>Home</h1>
     <h1>Home</h1>
     <h1>Home</h1>
     <h1>Home</h1>
     <h1>Home</h1> <h1>Home</h1>
     <h1>Home</h1>
     <h1>Home</h1>
     <h1>Home</h1>
     <h1>Home</h1>
     <h1>Home</h1>
  </main>
</template>
